import type { Metadata } from "next";
import { Geist_Mono } from "next/font/google";
import { climateCrisis, darumadropOne } from "./font";
import "./globals.css";

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${darumadropOne.className} ${geistMono.variable} ${climateCrisis.variable} ${darumadropOne.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
